### ISSUE TITLE
Apptentive is using apache, which does not exist on android M

### ISSUE THREAD

**Issue by mrhether** [apptentive/apptentive-android#103]
This means builds can not be made that target M and include apptentive. It also has some security concerns.

**Comment by skykelsey** [comment]
Thanks Mark. We are in the process of getting Android M support baked into the next release of our SDK. We will be migrating away from HttpClient in the next few weeks, and will update you then.

**Comment by skykelsey** [comment]
Hello Mark, we have released version 2.0.0, which removes use of `HttpClient` from our SDK.
