### ISSUE TITLE
Can't Use Apptentive with Design Support Library

### ISSUE THREAD

**Issue by solcott** [apptentive/apptentive-android#105]
When I try to use Apptentive 2.0.0 with the Android Design Support Library I get the following error message when I try to build my project.

Error:(2) Attribute "borderWidth" has already been defined

**Comment by skykelsey** [comment]
Hi Scott, thanks for reporting this. We are looking into fixing this, and I will keep you posted.

**Comment by skykelsey** [comment]
Hello Scott, we've released version 2.0.1 to properly namespace our custom attributes. This should avoid any future conflicts with other libraries. Please let me know if you have any more problems.
