### ISSUE TITLE
@style/ApptentiveTheme.Light does not exist

### ISSUE THREAD

**Issue by mrhether** [apptentive/apptentive-android#106]
But `@style/ApptentiveTheme` does. 

The integration guide mentions `@style/ApptentiveTheme.Light`.

**Comment by skykelsey** [comment]
Hello Mark,
You are right, the correct theme to use is `@style/ApptentiveTheme` if you want a light theme, or `@style/ApptentiveTheme.Dark` if you want to use a dark theme. I will update the documentation.

**Comment by mrhether** [comment]
Cool just an fyi :)
