### ISSUE TITLE
Transparent survey header on some devices

### ISSUE THREAD

**Issue by sguillen** [apptentive/apptentive-android#108]
The title of the survey has a transparent background on some devices, this happens on surveys that have many questions. The example had 16 questions.

**This is how the survey should look on all devices**
<img width="479" alt="screen shot 2015-09-25 at 14 35 52" src="https://cloud.githubusercontent.com/assets/6573208/10100736/0edd8e88-6394-11e5-8d82-e2561ad1685a.png">
<img width="483" alt="screen shot 2015-09-25 at 14 36 25" src="https://cloud.githubusercontent.com/assets/6573208/10100738/0ee0585c-6394-11e5-92d4-dcc44e1097a4.png">

**This is how it looks on some devices**

![screenshot_2015-09-25-14-27-56](https://cloud.githubusercontent.com/assets/6573208/10100737/0ee015f4-6394-11e5-881b-e3c34f226b65.png)
![screenshot_2015-09-25-14-28-07](https://cloud.githubusercontent.com/assets/6573208/10100739/0ee11f94-6394-11e5-8b80-41f6160487ed.png)

**Comment by barry-li** [comment]
Hi, Thank you for reporting this issue. To help us troubleshoot, may we know the api level of the problematic devices? Also if the survey questions are short, i.e. fit into one screen, do you see the same issue on those devices?

Barry

**Comment by sguillen** [comment]
This happens only with surveys that have many questions, it displays correctly when having fewer questions.

I have only managed to replicate on few devices:
* Samsung Galaxy S3 GT-I9300 -  API 16
* Samsung Galaxy S2 -  API 16
* HTC Incredible S - API 15

**Comment by skykelsey** [comment]
We have rolled out completely redesigned surveys with our 3.0 release, which fixes this issue. The new surveys follow Material Design guidelines, inherit the app theme, and allow overriding the styles applied to our UI independently as well. If you are able, please check 3.0.0 out.

https://github.com/apptentive/apptentive-android/blob/master/CHANGELOG.md
