### ISSUE TITLE
Hide all Apptentive branding does not work with Apptentive 2.0.1

### ISSUE THREAD

**Issue by IonutGavris** [apptentive/apptentive-android#113]
In message center there is an INFO button that opens a dialog with Apptentive information.

Looking trough the Apptentive source code it appears this button is always displayed.
This should be put behind a check that makes sure it will not appear when "Hide all Apptentive branding" is enabled.

Taking into consideration that you need to pay for this feature, it's kind of a rip off.

**Comment by filipmaelbrancke** [comment]
After paying for Apptentive, it's indeed something we would expect too...
