### ISSUE TITLE
Apptentive Message Center breaks on language change

### ISSUE THREAD

**Issue by ShotJP** [apptentive/apptentive-android#114]
Going into the message center I see the following...

<img width="279" alt="screen shot 2015-12-15 at 4 35 39 pm" src="https://cloud.githubusercontent.com/assets/5375066/11827534/114870e8-a34a-11e5-878d-8b0f79982565.png">

If I then change the language on the device to anything else (tested with a few different), I get nothing but the following...

<img width="274" alt="screen shot 2015-12-15 at 4 38 15 pm" src="https://cloud.githubusercontent.com/assets/5375066/11827566/4986bfc8-a34a-11e5-8102-1e3d2339c31f.png">

I've tried exiting, restarting, waiting, etc but this page won't load. Switching back to English immediately solves this. I've tried on version 2.0.1 and 2.1.0 and its happening on both. Let me know if this is potentially an account setting somewhere (I couldn't find one). Thanks

**Comment by skykelsey** [comment]
Hello Jason,

I'm sorry this is happening. I tried to quickly repro it, but couldn't. Would you mind sending me the logcat output to sky@apptentive.com? Hopefully that will allow me to diagnose the issue.

**Comment by ShotJP** [comment]
@skykelsey sent some logs to the email provided. Let me know if there is any other debugging to try or information you'd like me to collect

**Comment by ShotJP** [comment]
Thanks to some quick work from @skykelsey this was determined to be an issue in my account settings and not an SDK issue.
