### ISSUE TITLE
Message center doesn't support russian characters

### ISSUE THREAD

**Issue by AdamCopperfield** [apptentive/apptentive-android#115]
Tested on 2.1.1.
Send some message with russian characters, close activity, open again and you will see:
![image](https://cloud.githubusercontent.com/assets/5401297/12166230/704063e2-b535-11e5-90ac-4bd1d98dbe6e.png)
Take this string for testing: "что за хуйня пацаны, надо фиксить"

**Comment by barry-li** [comment]
Thanks for reporting this. We have released a new sdk version 2.1.2 to address the issue. Please update your app to use the latest version.
