### ISSUE TITLE
error: File is case-insensitive equivalent to: /Users/nguyenthixuyen/Work/Unity/PluginProject/apptentive-android-2.1.0/apptentive/res/values/integers.xml

### ISSUE THREAD

**Issue by xuyennguyen** [apptentive/apptentive-android#116]
Hello guys,
I'm want to integrate apptentive in my project. But when  I imported the apptentive example, when i run it , I got the errror.
I have no idea to fix it. Could you please help me check it?

**Comment by skykelsey** [comment]
Hello @xuyennguyen,

I'm sorry you're seeing this problem. Can you please contact me at sky@apptentive.com? I need to know what your app and build process are like. It looks like you are using Unity, which we don't support, but perhaps it's a quick fix I can help you with.

**Comment by luiyeas** [comment]
Hi!, I´ve the same error with the Eclipse Integration and this thread is closed but I can´t see the solution of this bug, how I can fix it?

Thanks.

**Comment by luiyeas** [comment]
PD: my log error;

/Users/Desktop/Proyectos/eclipse/replicapp-android/Libraries/apptentive/res/values-sw600dp/Integers.xml: error: File is case-insensitive equivalent:     same path
