### ISSUE TITLE
Use apply() instead of commit() when using SharedPreferences.Editor

### ISSUE THREAD

**Issue by solcott** [apptentive/apptentive-android#118]
I noticed that when you are editing SharedPreferences you are using commit()  In our tests commit takes about 10 milliseconds to write the changes to disk.  You should probably use apply() instead of commit().  apply() writes the changes to disk asynchronously.  The javadoc for [commit()](https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#commit()) states the following:

> If you don't care about the return value and you're using this from your application's main thread, consider using apply() instead.

**Comment by skykelsey** [comment]
Thanks Scott. We're planning on purging all the unnecessary synchronous commits in our next release. Thanks for bringing this to our attention.

**Comment by skykelsey** [comment]
This is implemented in 3.0.0. Enjoy!
