### ISSUE TITLE
Apptentive GCM notification behaving differently when app is in background. 

### ISSUE THREAD

**Issue by sarath-hotspot** [apptentive/apptentive-android#120]
When Apptentive GCM integration is enabled, and app is in background, app's GCM listener is not getting called. 

I integrated my android app with apptentive as per GCM instructions in https://docs.apptentive.com/android/integration/

When I reply to a message from apptentive web UI, I am observing two notification behaviors at app side.

When app is opened, my own GCM listener is getting called. When app is not in opened state, my own GCM listener is not getting called, however I am seeing a notification with app's default icon, "You have a new message" " ".

I am not sure who is creating this new/unwanted notification. It is causing problem because, clicking this new notification is taking user to my activity, but not opening message center.

Sdk version is 2.1.3
Device running Android 5.1.1

**Comment by aminelaadhari** [comment]
@skykelsey here the explanation on the issue http://stackoverflow.com/questions/35480573/gcmlistenerservice-is-not-called-when-application-is-in-background?rq=1

The server should send Data messages to allow customise the notifications.
It's very annoying...

**Comment by skykelsey** [comment]
Thanks for reporting this. We are looking into implementing a solution for this, and will be rolling one out in the near future.

**Comment by aminelaadhari** [comment]
@skykelsey any updates on this issue ?
we can't drop parse because of this

**Comment by skykelsey** [comment]
Hello Amine,

I'm sorry for the delay on this. We are investigating a fix in the current sprint, so hopefully we will be able to provide a solution in the next couple weeks, although I can't promise. We are working on improvements to how we handle push in general that should make integration simpler as well.

**Comment by aminelaadhari** [comment]
Hello @skykelsey. Any news about this ?

**Comment by msaffitz** [comment]
We are in the final stages of testing a release of the SDK that will resolve this issue, and I anticipate it being available within the next couple of weeks.  Please keep an eye on our GitHub repository for availability.

**Comment by skykelsey** [comment]
Fixed in 3.3.0. Please let me know if you have any problems upgrading.
