### ISSUE TITLE
why is GlobalInfo.apiKey written to the logs as an info message?

### ISSUE THREAD

**Issue by ericsavage** [apptentive/apptentive-android#121]
Why is the GlobalInfo.apiKey written to the logs as an info message?
We are told in `settings/api` to *Keep your API key secret.*

<img width="720" alt="screen shot 2016-04-24 at 11 51 21 am" src="https://cloud.githubusercontent.com/assets/5480417/14769709/b78959b0-0a13-11e6-8ce8-f69554a6dfd5.png">

https://github.com/apptentive/apptentive-android/blob/master/apptentive/src/com/apptentive/android/sdk/Apptentive.java#L1003
```Log.i("API Key: %s", GlobalInfo.apiKey);```

**Comment by skykelsey** [comment]
Hi Eric,

The API Key is not actually as sensitive as our instructions make it out to be, but I will make sure we aren't logging it in a future release. I'll have the instructions updated to make it more clear.

Thanks!
