### ISSUE TITLE
NullPointerException at Util.getThemeColor(Util.java:472)

### ISSUE THREAD

**Issue by GlebMaltsev** [apptentive/apptentive-android#125]
Hello. Is it known issue? (Android 4.3)

`Fatal Exception: java.lang.NullPointerException
       at com.apptentive.android.sdk.util.Util.getThemeColor(Util.java:472)
       at com.apptentive.android.sdk.module.engagement.interaction.fragment.ApptentiveBaseFragment.onViewCreated(ApptentiveBaseFragment.java:268)
       at com.apptentive.android.sdk.module.engagement.interaction.fragment.MessageCenterFragment.onViewCreated(MessageCenterFragment.java:227)`

[Click to see full stacktrace](https://gist.github.com/GlebMaltsev/9e8ad2b9a21ddd114aa7588b0d0276ca)

**Comment by skykelsey** [comment]
Hello @GlebMaltsev, can you please help me by answering a few questions?

* Which version of the Apptentive SDK are you using?
* Are you using an AppCompat theme for your entire Application, and if so, which one?

Thanks!

**Comment by GlebMaltsev** [comment]
@skykelsey, I use Apptentive SDK 3.0.0 version and "Theme.AppCompat" as parent theme for my application theme.

Unfortunately, i can't reproduce this issue on any of my devices. I have only one crash report from SGH-T999 device (Samsung Galaxy S III T-Mobile) running on android 4.3. So i can't confirm or refute that on latest version of Apptentive SDK this issue was fixed.

**Comment by skykelsey** [comment]
Hi @GlebMaltsev,

It turns out this has been fixed since 3.0.1, so if you haven't upgraded to the latest version, doing so will fix the problem. Thanks for reporting this.

**Comment by GlebMaltsev** [comment]
@skykelsey. thanks.
