### ISSUE TITLE
Why do you require multidex to be enabled?

### ISSUE THREAD

**Issue by davidschreiber** [apptentive/apptentive-android#126]
Why does `apptentive-android` enable `multiDex = true` inside the `build.gradle` (https://github.com/apptentive/apptentive-android/blob/master/apptentive/build.gradle#L26)? 

Native multidex support was only added Android Lollipop. Prior versions of Android require the `com.android.support:multidex` library to make multidex work, which is added as transitive dependency. The multidex support library has its own share of limitations: https://developer.android.com/studio/build/multidex.html#limitations

Does Apptentive really require multidex support? To me this seems like an unnecessary addition (that is pushed to the implementing app).

**Comment by skykelsey** [comment]
Hello @davidschreiber ,

I believe that we can remove this flag. I don't think it should have been included in the first place. I'm sorry this is delaying your integration. I'll do some testing, and most likely remove it in the next patch release.

**Comment by skykelsey** [comment]
We've released 3.2.2, which fixes this issue. It should be available on central maven within a few hours.
