### ISSUE TITLE
NullPointerException at MessageCenterComposingView.addImagesToImageAttachmentBand(java.util.List)

### ISSUE THREAD

**Issue by GlebMaltsev** [apptentive/apptentive-android#128]
Hello. I have crash on both 3.0.0 and 3.2.2 versions of apptentive SDK. Reproduced 10/10 on ~~Samsung Galaxy Note 3 Android 5.0~~ any device.

Steps to reproduce:
1. ~~Switch off the internet connection~~ Switch on "Do not keep activities" in developer options.
2. Open apptentive activity (Apptentive.showMessageCenter(getActivity())).
3. Press "add new message" button in right bottom corner (or use showing form if you never send message before).
4. Click "add attachment" button and switch any picture - crash will appear:

java.lang.RuntimeException: Unable to resume activity {com.spritzr/com.apptentive.android.sdk.ApptentiveViewActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65546, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:2314 flg=0x43 }} to activity {com.spritzr/com.apptentive.android.sdk.ApptentiveViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.apptentive.android.sdk.module.messagecenter.view.MessageCenterComposingView.addImagesToImageAttachmentBand(java.util.List)' on a null object reference

[Click to see full stacktrace](https://gist.github.com/GlebMaltsev/aeadbdb08920b729da6d4dbe2421628e)

Thanks!

**[UPDATED]** I discover that the real reason of appearance of this bug is killing an activity in background. I edit issue description above.

**Comment by weeeBox** [comment]
Fixed in v5.0.4
