### ISSUE TITLE
Rating prompt not showing with sample app.

### ISSUE THREAD

**Issue by chrisanderson79** [apptentive/apptentive-android#131]
When creating an account and trying to show a rating prompt with the sample app the rating is never shown.

This appears to be due to the code_point/rating_dialog.remind/last_invoked_at/total failing in the evaluation.

How do we set this? It doesn't seem to be on the rating dialog form.

01-27 12:32:11.905 3787-3787/com.apptentive.android.example V/Apptentive:     - code_point/rating_dialog.remind/last_invoked_at/total
01-27 12:32:21.348 3787-3787/com.apptentive.android.example V/Apptentive:       - null $before BigDecimal(-86400)?
01-27 12:32:27.961 3787-3787/com.apptentive.android.example V/Apptentive:         - => false

**Comment by skykelsey** [comment]
Hi Chris,

The RatingDialog is only shown after the EnjoymentDialog, or after a delay if a user previously selected "Remind" on the RatingDialog the first time it was shown. Are you able to see the EnjoymentDialog? Please send me complete logs at sky@apptentive.com, and I will try to help you out.
