### ISSUE TITLE
Updating android platform compile sdk to android-p causes 'attr/textColorError' not found error

### ISSUE THREAD

**Issue by breakingthebuild** [apptentive/apptentive-android#149]
When updating our android platform compile sdk to `android-p`, we are getting this error 'attr/textColorError' not found. This line is the culprit: 

https://github.com/apptentive/apptentive-android/blob/master/apptentive/src/main/res/values/themes.xml#L150

```
<!-- Needed since design support library 23.2.0 -->
<item name="textColorError">@color/apptentive_validation_failed_color</item>
```

**Comment by weeeBox** [comment]
Hey @breakingthebuild. Sorry for the late reply: we're looking at the issue right now.

**Comment by weeeBox** [comment]
@breakingthebuild, which `buildToolsVersion`, `targetSdkVersion` and `minSdkVersion` do you use? Would you be able to share your `build.gradle` file?

**Comment by breakingthebuild** [comment]
@weeeBox Thanks for looking into this issue. Below are the gradle settings you asked for:

```
minSdkVersion = 21
buildToolsVersion = 27.0.3
targetSdk = 26
```

**Comment by weeeBox** [comment]
@breakingthebuild, we're not able to reproduce the issue on our end. I've created a small test project with the same configuration as yours. Would you be able to check if you can build it?

It would also be helpful if you can send us your `build.gradle` file.

[Test-Apptentive.zip](https://github.com/apptentive/apptentive-android/files/1891333/Test-Apptentive.zip)

**Comment by weeeBox** [comment]
Thanks @ThePromoter.

We'll take a look at it

**Comment by breakingthebuild** [comment]
@weeeBox Hey Sorry for the lack of response on my part. Curious if you were able to reproduce this issue?

**Comment by weeeBox** [comment]
@breakingthebuild, yes, I was able to reproduce it. Looking for a solution now...

**Comment by breakingthebuild** [comment]
@weeeBox Awesome! Thanks for the quick response.

**Comment by weeeBox** [comment]
Hi, @breakingthebuild.

Here's a temporary fix (will incorporate it in the next SDK release):
Create a new xml file `<your_app_module>/src/main/res/values-v27/apptentive-attrs-fix.xml` with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="ApptentiveThemeTemplate">
        <attr name="textColorError" format="color|reference"/>
    </declare-styleable>
</resources>
```

Let me know if it helps!

**Comment by breakingthebuild** [comment]
That worked. Thanks @weeeBox

**Comment by weeeBox** [comment]
Great! Thanks for your help! The fix is available in 5.1.4 release

**Comment by lennonpetrick** [comment]
Hey guys, I have the same issue in my project.
It seems appcompat has changed `textColorError ` attribute. Now it's using `colorError` instead.

**Comment by weeeBox** [comment]
Hi @lennonpetrick,

What are your `compileSdkVersion`, `buildToolsVersion` and `targetSdkVersion`?

**Comment by lennonpetrick** [comment]
It's `compileSdkVersion  28` , `buildToolsVersion  27.0.3` and `targetSdkVersion 28`.

I think you misunderstood me lol. I am not using your product.
I was just looking for a solution for my problem when I came across with this git issue. So after finding the solution I thought would be good to comment here for helping someone else.

**Comment by weeeBox** [comment]
Hey @lennonpetrick,

Yes, I've totally misread that 🤦! Thanks for your hint, we'll take a closer look!
