### ISSUE TITLE
API 27 removes method resulting in crash

### ISSUE THREAD

**Issue by seantimm** [apptentive/apptentive-android#161]
IntentCompat.makeRestartActivityTask has been removed in API 27, so Apptentive now crashes the app when opening and then clicking back when targeting API 27.

https://developer.android.com/sdk/support_api_diff/27.0.0/changes/android.support.v4.content.IntentCompat

**Comment by weeeBox** [comment]
Hi @seantimm,

Sorry for the issue. Which version of Apptentive SDK have you been using? Would you be able to attach your `build.gradle` file?

-Alex

**Comment by seantimm** [comment]
Version 3.4.1

**Comment by seantimm** [comment]
Latest version resolves the problem, so I'm going to close this.  I'm still not sure why it wouldn't list as a dependency update, but we're good to go!  Thanks!

**Comment by weeeBox** [comment]
No problem! Glad it helps!
