### ISSUE TITLE
This provider is subject to path traversal attacks.

### ISSUE THREAD

**Issue by hbloom1783** [apptentive/apptentive-android#164]
If this provider gets exported by an app, it gives read access to the app's entire file system to anyone who can broadcast intents on the same device.  Per https://support.google.com/faqs/answer/7496913, an example of an attack URI would be "content://it.my.app.ApptentiveAttachmentFileProvider/%2F..%2F..path%2Fto%2Fsecret.txt".

**Comment by weeeBox** [comment]
Hey @hbloom1783,

Thanks for reporting that. We'll take a closer look.

**Comment by weeeBox** [comment]
Fixed in `5.1.1`
