### ISSUE TITLE
(android:maxSdkVersion="18") for WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by gmbett** [apptentive/apptentive-android#168]
On latest Apptentive version you added the above attribute. 

That property breaks the permission request process for those applications that are targeting API 26 and are requesting READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE storage permissions.

https://developer.android.com/about/versions/oreo/android-8.0-changes#rmp

**Comment by gmbett** [comment]
It can be fixed if you add:
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>

But anyway... you shouldn't do that

**Comment by weeeBox** [comment]
Hi @gmbett,

It was [added](https://github.com/apptentive/apptentive-android/blob/master/apptentive/src/main/AndroidManifest.xml#L14) in version 5.1.4. Doesn't it work for you as expected?

**Comment by gmbett** [comment]
If I don't add the **tools:node="replace"** the permission request fails immediately.

**Comment by weeeBox** [comment]
Sorry for the inconvenience. We'll look at it and get back to you.

**Comment by weeeBox** [comment]
Hi @gmbett,

We're trying to reproduce the issue on our end. Would you be able to provide more implementation details (like your `build.gradle` file or even a small test project). That would be very helpful!

**Comment by gmbett** [comment]
Hi @weeeBox 

I have created a sample project to show you the issue.
Please check: https://github.com/gmbett/storagepermissionissue

If you have any questions please feel free to ask them !

**Comment by weeeBox** [comment]
Thanks!

**Comment by weeeBox** [comment]
Hi @gmbett,

I can see the issue now. It seems like other lib developers are experiencing this, too. We would update our docs and ask people to override permission in their manifest:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

This article explains it better: https://commonsware.com/blog/2018/04/09/manifest-merger-maxsdkversion-missing-permission.html

**Comment by gmbett** [comment]
Ok, thanks for checking this issue. 👍
