### ISSUE TITLE
Libray not working with Android P (traget 28 and JDK compiler 1.8)

### ISSUE THREAD

**Issue by vinayakkumar** [apptentive/apptentive-android#169]
Hi Team ,

Aptentive 5.3.0 is not working Android P ie target and compile version 28 and JD version 1.8 

We are facing random error so please make sure your libray is compatable with Android P ie Target version 28

**Comment by weeeBox** [comment]
Hi @vinayakkumar,

What kind of errors are you facing? Can you also provide the contents of your `build.gradle` file?

**Comment by stephan-mediamonks** [comment]
@weeeBox We have a similar setup, AppTentive SDK 5.3.0, target 28, running on Android Pie emulator.

[Here](https://drive.google.com/open?id=1I4w9VOktuTq5cH4RUFoN1VoqtTsLQJHu) is an export of LogCat, filtered for "AppTentive". Hope that gives you more data. If helpful we can share more project setup details.

**Comment by weeeBox** [comment]
Thanks, @stephan-mediamonks. We'll take a look and get back to you ASAP

**Comment by weeeBox** [comment]
Hey @stephan-mediamonks,

Would you be able to provide the contents of your `build.gradle` file?

**Comment by stephan-mediamonks** [comment]
Hi Alex,

I’ve attached a zip with both the project level build gradle and the app level build gradle.



Two more comments:

the logcat is actually from an emulator running Android 8.1, not Android 9
the project includes DexGuard. We did not update any Proguard / Dexguard rules when updating to SDK 5.3

Regards,

--
Stephan Bezoen · Lead Mobile Monk at MediaMonks
LA · NY · MX · BA · SP · LDN · AMS · STO · DXB · SG · SH
Call our Amsterdam office on +31356212150.
Reach me directly at stephan@mediamonks.com <mailto:steven@mediamonks.com>.

**Comment by weeeBox** [comment]
Hi @stephan-mediamonks,

I can't see any attachments.

**Comment by weeeBox** [comment]
Hi @stephan-mediamonks,

We're able to reproduce the issue after updating `platform-tools` to `28.0.1` and `emulator` to 28.0.3`. Everything works find on a real device. Do you have API 27 devices to verify?

**Comment by weeeBox** [comment]
Hey @ stephan-mediamonks,

Did you have a chance to check this out?

**Comment by weeeBox** [comment]
Fixed in 5.3.1
