### ISSUE TITLE
Survey is covered in focus overlay

### ISSUE THREAD

**Issue by sicklepilot** [apptentive/apptentive-android#187]
Tested on Android 8, 9 and 10

When you create a survey that can goes past the bottom of the screen, needing to be scrolled, a yellow overlay appears when you tap on the survey or scroll. This goes away when you hit tab and moves to the next focusable item. I believe the code causing this issue is related to focus resetting code found here: https://github.com/apptentive/apptentive-android/blob/master/apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/SurveyFragment.java#L251-L260

A screenshot to show an example of this issue is located in this issue. Parts are redacted for privacy. 
![Screenshot_20190827-005911](https://user-images.githubusercontent.com/51972200/64345170-d6bd2780-cfbd-11e9-9543-662660accb1a.png)

**Comment by CaseyApptentive** [comment]
Thanks for the thorough report @sicklepilot. I'd be happy to look into this for you. Which version of our SDK are you using?

**Comment by sicklepilot** [comment]
Hey Casey! We’re experiencing this on 5.4.5 and 5.4.6 for sure. Im unable to test other versions due to a crash in older libraries on the survey fragment.

Thanks for investigating this!

**Comment by CaseyApptentive** [comment]
Thanks, @sicklepilot! Mind emailing me at casey@apptentive.com with more info on the specific app you're working on? I'd like to keep your Customer Success Manager in the loop as well, if relevant. 

Appreciate the help tracking this down.

**Comment by bimalchawla** [comment]
Hi @CaseyApptentive @sicklepilot  , i checked this issue on latest 5.5.0 apptentive sdk on android version 9, this issue still occuring.

**Comment by CaseyApptentive** [comment]
Hi @bimalchawla. Thanks for the report. Can you send us the contents of your build.gradle?

Also, is this your first time adding Apptentive to your app or are you migrating from an older SDK version?

Thanks!

**Comment by sicklepilot** [comment]
Hi Casey, Bimal is with my organization and this is the same app.

**Comment by bimalchawla** [comment]
Hi @CaseyApptentive any update on above issue.

**Comment by CaseyApptentive** [comment]
Hi @bimalchawla, very sorry for the delay. I have a ticket for my Android team and will let you know as soon as possible. 

Is this preventing you from release?

**Comment by bimalchawla** [comment]
Not really @CaseyApptentive. But we are waiting for library update to resolve this issue in our app. Thanks.

**Comment by CaseyApptentive** [comment]
Thanks for your patience. I'll let you know as soon as our engineers have made progress. 

Let me know if there's anything else I can do for you.

**Comment by bimalchawla** [comment]
Thanks for the update. Waiting for library update.

**Comment by sicklepilot** [comment]
We found a workaround by adding the following line to our AppTentive theme override

```
<item name="android:colorControlHighlight">@android:color/transparent</item>
```

**Comment by CaseyApptentive** [comment]
Thank you for confirming @sicklepilot !

Let me know if there's anything further I can help with.
