### ISSUE TITLE
Love dialog is not showing for Rating Prompt

### ISSUE THREAD

**Issue by FazalHussain** [apptentive/apptentive-android#197]
I am trying to integrate Apptentive in my android app but love dialog is not showing whereas the event is getting tracked 

```
Apptentive.setRatingProvider(CustomRatingProvider())
        AnalyticHelper.logApptentiveEvent(this,
                AnalyticsConstants.APPTENTIVE.OFFER_DETAIL)
```

What I am doing wrong?

**Comment by CaseyApptentive** [comment]
Hey @FazalHussain! 

Can you email me at support@apptentive.com with details about which app you're working on? I'd like to take a closer look at your Dashboard settings. 

Also, can you share logs from a test in which you attempt to launch the Love Dialog?

Thanks.
