### ISSUE TITLE
No Rating dialog pops up after tapping yes on Love Dialog

### ISSUE THREAD

**Issue by aielcbmDev** [apptentive/apptentive-android#222]
Hi there,

The Rating Dialog does not appear after clicking yes on the Love Dialog on the following Apptentive SDK versions:
- 5.6.0
- 5.6.1
- 5.6.2

The latest version that displays the Rating Dialog after clicking yes the Love Dialog is 5.5.4.

The Love Dialog is configured as described here:
<img width="615" alt="ApptentiveLoveDialogHowOften" src="https://user-images.githubusercontent.com/30575019/109173068-596e0f80-777b-11eb-80b3-14ca46e1f50a.png">

Thanks in advance.

**Comment by CaseyApptentive** [comment]
Hi @aielcbmDev. Thanks for the thorough report. 

Starting in SDK 5.6.0, we added support for the new "Google Play Rating Dialog". This is an in-app rating prompt -- and it works really well. The downside with this new tool is that test it can be more difficult. 

To be clear: Apptentive controls when this dialog is attempted to be shown, who it's shown to, and where it's surfaced. But Google has the final say on whether it can actually be displayed or not. And Google has some rules that that restrict how it's tested. 

So, what you're seeing sounds like the behavior seen here: https://learn.apptentive.com/knowledge-base/troubleshooting-the-apptentive-android-sdk/#google-play-rating-dialog-not-shown

We'd have to look in verbose logs to be certain, but it sounds like you may be hitting one of those known restrictions for testing. 

The best way to test this is to use "Google Play Internal App Sharing". This allows you to share pre-production builds of the app with specific testers. Those testers can see the Google Play Rating Dialog and interact with it, though they are unable to leave a real review (the button will be grayed out).

Another way would be to use a "Google Play Internal Test Track". This option works as well, but there's one caveat. Testers should not actually leave a review using this message or else it will preclude them from ever being eligible to see the Google Play Rating Dialog again. 

Both methods are outlined here: https://developer.android.com/guide/playcore/in-app-review/test

Will either of those solutions work for you?

**Comment by aielcbmDev** [comment]
Hi @CaseyApptentive, thank you for your fast reply!

**Comment by CaseyApptentive** [comment]
No problem. Let me know if you need anything else.
