### ISSUE TITLE
Event 'com.apptentive#app#launch' for a version is not 0 on fresh install

### ISSUE THREAD

**Issue by cweggler** [apptentive/apptentive-android#223]
Hello Apptentive Team,

We have a Love Dialog in our app that is set to show once to a user after 5 launches of the app if the `person_data` `user_30_days` is true, and the invokes for event `com.apptentive#EnjoymentDialog#launch` is  0. However in our latest release, our quality analyst noticed that the Love dialog actually displayed on the first launch of the fresh install of our latest release.

In debugging, looking at the Apptentive Logs where `config.logLevel = ApptentiveLog.Level.VERBOSE`, I was also able to reproduce this issue in our debug environment on a Google Pixel Emulator with OS: Android 8 (API 26).

I have attached a txt file with the logs. But notice the line 
`com.apptentive#app#launch for version name myfiles-p3 (2) is greater than or equal to 2` 
That wouldn't be weird except this launch was on a fresh install of the app, so it shouldn't have had any previous launches at all and should evaluate to (0).

Please let me know if you need any more information to look into this issue or have suggestions for our team to try out! Thank you!
[apptentiveLogsWithBug.txt](https://github.com/apptentive/apptentive-android/files/6198726/apptentiveLogsWithBug.txt)

**Comment by CaseyApptentive** [comment]
Hi @cweggler. Thanks for the thorough report. There don't appear to be any known issues related to this. 

Typically uninstalling + reinstalling should reset all counts, as you and your team did. Is this issue easy for you to reproduce?

If so and it wouldn't be too much of an ask, one other thing you could try is clearing the app cache. To do this, have the app installed on your test device and have it fully closed (not backgrounded) > long tap the app icon > App Info > Storage & cache > Clear Storage and hit okay. 

![Screenshot_20210325-153034](https://user-images.githubusercontent.com/29615280/112551952-29685b00-8d7f-11eb-9a77-0ad94d424997.png)

Then launch the app and try to launch the Love Dialog again. We'd expect this to make the count start back at zero, so it would take several launches for you to see the Love Dialog.

Let me know if that works.

**Comment by CaseyApptentive** [comment]
Perfect. Thanks for confirming.
