### ISSUE TITLE
Cannot figure out how to configure Apptentive "About" dialog buttons.

### ISSUE THREAD

**Issue by elliottj-accolade** [apptentive/apptentive-android#235]
Apptentive v. 5.8
Android 12, Pixel 5

- [x] I have reviewed the documentation for how to configure Apptentive's UI [here](https://learn.apptentive.com/knowledge-base/android-interface-customization/#overriding-our-styles).

Hello,

We have an issue where the Apptentive buttons on the [apptentive_about](https://github.com/apptentive/apptentive-android/blob/master/apptentive/src/main/res/layout/apptentive_about.xml) fragment are not displaying. We have a complicated theme that supports both dark and light modes. Unfortunately this has made it very hard to diagnose exactly which override is causing the problem. 

On an empty project, buttons appear no issues:
![Screenshot_20220118-154834](https://user-images.githubusercontent.com/40704634/150037618-5f8e59a8-75a4-454d-a8be-df13c95ba1a9.png)

On our project, buttons do not appear:
![Screenshot_20220118-154814](https://user-images.githubusercontent.com/40704634/150037646-65ca081b-3e6a-4231-9811-df3b3cf1cc22.png)

I've browsed around in the layout file and found that the buttons both use a style of [Apptentive.Widget.Button.Borderless](https://github.com/apptentive/apptentive-android/blob/758a8cd3af00f13fd1d8244bafa45e2f6c0bf9b7/apptentive/src/main/res/values-v21/styles.xml#L70-L78), and a `textAppearance` of [Apptentive.TextAppearance.Body1](https://github.com/apptentive/apptentive-android/blob/758a8cd3af00f13fd1d8244bafa45e2f6c0bf9b7/apptentive/src/main/res/values-v21/styles.xml#L44-L47). I haven't had any luck in overwriting any of the values in either of those themes. 

Do you have any suggestions of what values I can override to change that? I notice in an empty project that setting `colorPrimary` on the `ApptentiveThemeAbout` works, but it didn't work in the heavily themed project.

BTW, I acknowledge this smells like a fishing expedition. I'm hoping for a direction other than what I mentioned above.

**Comment by CaseyApptentive** [comment]
Hi @elliottj-accolade. Great question. Sometimes that section does have trouble with more complex styles, especially in dark mod.

My immediate thought is that you may want to simply remove the (i) info button. Would that fit your needs? Details on how to do that: 
___________

You'd need to override the theme res/values/themes-apptentive-override.xml. This will hide the (i) button in both Message Center and Surveys. 

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Apptentive.Style.Widget.ImageButton.Info">
        <item name="android:visibility">invisible</item>
    </style>
</resources>
```

**Comment by elliottj-accolade** [comment]
Hi @CaseyApptentive, that works for us. Thank you for the suggestion!

**Comment by CaseyApptentive** [comment]
Happy to help. Let me know if you need anything else.
