### ISSUE TITLE
Apptentive dialog disappears on screen rotation

### ISSUE THREAD

**Issue by gkee42** [apptentive/apptentive-android#83]
When the user has the rating dialog open, if they rotate the device, the dialog disappears.

Seems to be device specific (can only reproduce on some phones).
Tested On : Samsung Galaxy Grand 2 (Android v4.3)
Using Apptentive for Android v1.4.2

**Comment by skykelsey** [comment]
Our dialogs have been redesigned, and should no longer exhibit this issue.
