### ISSUE TITLE
Allow hiding the email field from the end user if we already know it

### ISSUE THREAD

**Issue by mjerdely** [apptentive/apptentive-android#88]
Please create an option is hide the email field (like on the iOS library) if we already know what it is.

Currently the code will only pre-populate the field but will continue to show it unless the user enters this themselves.

Below is the snippet from the library that controls this logic:

```
String personEnteredEmail = PersonManager.loadPersonEmail(activity);
String personInitialEmail = PersonManager.loadInitialPersonEmail(activity);
if (Util.isEmpty(personEnteredEmail)) {
	if (!Util.isEmpty(personInitialEmail)) {
		dialog.setEmailFieldHidden(false);
		dialog.prePopulateEmail(personInitialEmail);
	}
} else {
	dialog.setEmailFieldHidden(true);
}
```

**Comment by skykelsey** [comment]
Hello Michael,

We have released a new version of our SDK (2.0.0) that simplifies Message Center and removes the Feedback Dialog. Please let me know what you think.
