### ISSUE TITLE
Getting error  Style Resource definition cycle

### ISSUE THREAD

**Issue by spectrumColors** [apptentive/apptentive-android#93]
Getting this error at time of making Sing APK 

Error: Style Resource definition cycle: ApptentiveHeader => ApptentiveHeader.Plain => ApptentiveHeader [ResourceCycle]
Error: Style Resource definition cycle: ApptentiveHeaderText => ApptentiveHeaderText.Plain => ApptentiveHeaderText.Default => ApptentiveHeaderText [ResourceCycle]
Error: Style Resource definition cycle: ApptentiveMainArea => ApptentiveMainArea.Plain => ApptentiveMainArea [ResourceCycle]
Error: Style Resource definition cycle: ApptentiveMessageCenterDrawer => ApptentiveMessageCenterDrawer.Plain => ApptentiveMessageCenterDrawer [ResourceCycle]

**Comment by skykelsey** [comment]
Hello,

The styles causing your problem no longer exist. Please use the most current release of the SDK, and let me know if you have any further problems with styles.

**Comment by naveedahmad99** [comment]
Here is the solution : http://stackoverflow.com/a/36109905/2915785
