### ISSUE TITLE
Add ability to turn off Apptentive logs programmatically

### ISSUE THREAD

**Issue by Den-Rimus** [apptentive/apptentive-android#94]
And, please - don't tell me to set up my LogCat filter in IDE - sometimes this can be inconvenient.

**Comment by skykelsey** [comment]
Hi Den,

We actually recently added this ability. Instructions are [here](http://www.apptentive.com/docs/android/integration/#logging).

**Comment by Den-Rimus** [comment]
Huge thanks! Sorry for bother
